### Listar Usuarios ###
GET https://localhost:7278/api/usuario/listar

### Criar Usuario ###
POST https://localhost:7278/api/usuario/cadastrar
Content-Type: application/json

{
    "nome": "João",
    "dataNascimento": "2002-06-19"
}